# Generated by Django 4.1.7 on 2023-04-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryType', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('I', 'Income'), ('O', 'Expenses')], default='O', max_length=1)),
                ('itemCategoryName', models.CharField(max_length=1000)),
                ('itemName', models.CharField(max_length=1000)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
