# Generated by Django 4.2 on 2023-04-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=30),
        ),
    ]
